In [ ]:
import pandas as pd

df_algorithm = pd.read_csv("algorithm_results.csv")
df_column = pd.read_csv("results.csv")
df_true = pd.read_csv("true_results.csv")
df_new_server_results = pd.read_csv("new_results_server.csv")

df_merged = pd.merge(df_algorithm, df_column, on=['N', 'M'], how='outer')
df_merged = pd.merge(df_merged, df_true, on=['N', 'M'], how='outer')
# print(df_merged.head())
df_merged['difference'] = df_merged['BOUNDS_SIZE'] - df_merged['ALGO_BOUNDS_SIZE']
df_merged['difference']
df_merged.to_csv("merged_bounds.csv", index=False)

df = pd.DataFrame()
# df['COLUMN_GEN'] = True if isinstance(df_merged['LOWER_BOUND'], float) else False
# df['ALGORITHM'] = True if isinstance(df_merged['LOWER_BOUND'], float) else False
df['N'] = df_merged['N']
df['M'] = df_merged['M']
df['COLUMN_GEN'] = df_merged['LOWER_BOUND'].notna()
df['ALGORITHM'] = df_merged['ALGO_LOWER_BOUND'].notna()
df['CG_LOWER'] = df_merged['LOWER_BOUND']
df['CG_UPPER'] = df_merged['UPPER_BOUND']
df['DIFF_LOWER'] = df_merged['LOWER_BOUND']-df_merged['ALGO_LOWER_BOUND']
df['DIFF_UPPER'] = df_merged['UPPER_BOUND']-df_merged['ALGO_UPPER_BOUND']
df['TRUE_VALUE'] = df_merged['TRUE_VALUE']
df['CG_TIME'] = df_merged['LOWER_BOUND_SECONDS_TAKEN']+df_merged['UPPER_BOUND_SECONDS_TAKEN']
df['ALGORITHM_TIME'] = df_merged['ALGO_BOUNDS_SECONDS_TAKEN']
df['CG_LOWER_Ite'] = df_merged['LOWER_BOUND_REQUIRED_ITERATIONS']
df['CG_UPPER_Ite'] = df_merged['UPPER_BOUND_REQUIRED_ITERATIONS'].astype(int)
df['CG_BOUNDS_SIZE'] = df_merged['BOUNDS_SIZE']

In [52]:
df

,N,M,COLUMN_GEN,ALGORITHM,CG_LOWER,CG_UPPER,DIFF_LOWER,DIFF_UPPER,TRUE_VALUE,CG_TIME,ALGORITHM_TIME,CG_LOWER_Ite,CG_UPPER_Ite,CG_BOUNDS_SIZE
0,1,1,True,True,0.108661,0.126589,0.000000e+00,0.000000e+00,0.117192,0.017472,0.661149,7,6,0.017929
1,2,1,True,True,0.539263,0.741965,-1.110223e-16,-1.110223e-16,0.543601,0.257396,1.548771,13,14,0.202702
2,3,1,True,True,0.103558,0.123781,0.000000e+00,-9.714451e-17,0.115301,3.121716,106.186425,46,34,0.020223
3,4,1,True,True,0.535113,0.765015,1.110223e-16,-2.220446e-16,0.537535,45.201639,410.559574,77,120,0.229903
4,5,1,True,True,0.097862,0.119765,0.000000e+00,-1.110223e-16,0.109848,1047.445045,7173.897312,393,227,0.021903
5,1,2,True,True,0.108871,0.128433,0.000000e+00,0.000000e+00,0.118882,0.084182,4.649352,16,11,0.019562
6,2,2,True,True,0.551997,0.617712,0.000000e+00,-1.110223e-16,0.555954,1.276739,2493.832186,40,36,0.065715
7,1,3,True,True,0.107029,0.126854,0.000000e+00,-1.110223e-16,0.116733,0.206602,4206.929769,86,55,0.019824
8,3,2,True,False,0.095657,0.117456,NaN,NaN,0.106307,94.491853,NaN,198,165,0.021799
9,4,2,True,False,0.546623,0.621961,NaN,NaN,0.553581,4359.927188,NaN,834,599,0.075338
10,2,3,True,False,0.546848,0.615166,NaN,NaN,0.551603,6.642606,NaN,142,119,0.068317
11,3,3,True,False,0.103332,0.123310,NaN,NaN,0.115515,3138.142384,NaN,1651,1591,0.019978

In [35]:
print(1047/3600)
print(7173/3600)

0.29083333333333333
1.9925

In [13]:
import pandas as pd
df_gc_ori = pd.read_csv("results.csv")
df_gc_ori['TOTAL_SECONDS_TAKEN'] = df_gc_ori['LOWER_BOUND_SECONDS_TAKEN']+df_gc_ori['UPPER_BOUND_SECONDS_TAKEN']
df_gc_ori.to_csv("treated_results.csv", index=False)
df_gc_ori = df_gc_ori.drop(columns=['LOWER_BOUND_SECONDS_TAKEN', 'UPPER_BOUND_SECONDS_TAKEN'])
df_gc_new_res = pd.read_csv("new_results_server.csv")
# df_gc = pd.merge(df_gc_ori, df_gc_new_res, on=['N', 'M'], how='outer')
df_gc = pd.concat([df_gc_ori, df_gc_new_res], ignore_index=True)
df_gc['UPPER_BOUND_REQUIRED_ITERATIONS'] = df_gc['UPPER_BOUND_REQUIRED_ITERATIONS'].astype(int)
df_gc

,N,M,LOWER_BOUND,LOWER_BOUND_REQUIRED_ITERATIONS,UPPER_BOUND,UPPER_BOUND_REQUIRED_ITERATIONS,BOUNDS_SIZE,TOTAL_SECONDS_TAKEN
0,5,1,0.097862,393,0.119765,227,0.021903,1047.445045
1,3,2,0.095657,198,0.117456,165,0.021799,94.491853
2,4,2,0.546623,834,0.621961,599,0.075338,4359.927188
3,1,3,0.107029,86,0.126854,55,0.019824,0.206602
4,2,3,0.546848,142,0.615166,119,0.068317,6.642606
5,3,3,0.103332,1651,0.123310,1591,0.019978,3138.142384
6,1,1,0.108661,7,0.126589,6,0.017929,0.749369
7,2,1,0.539263,13,0.741965,14,0.202702,0.270833
8,3,1,0.103558,46,0.123781,34,0.020223,1.814951
9,4,1,0.535113,77,0.765015,107,0.229903,15.974915
10,1,2,0.108871,16,0.128433,11,0.019562,0.215571
11,2,2,0.551997,40,0.617712,36,0.065715,0.866675

In [19]:
import pandas as pd

df_algorithm = pd.read_csv("algorithm_results.csv")
df_true = pd.read_csv("true_results.csv")

df_merged = pd.merge(df_gc, df_algorithm, on=['N', 'M'], how='outer')
df_merged = pd.merge(df_merged, df_true, on=['N', 'M'], how='outer')
# print(df_merged.head())
df_merged['difference'] = df_merged['BOUNDS_SIZE'] - df_merged['ALGO_BOUNDS_SIZE']
df_merged['difference']
df_merged.to_csv("refactored_merged_bounds.csv", index=False)

df = pd.DataFrame()
# df['COLUMN_GEN'] = True if isinstance(df_merged['LOWER_BOUND'], float) else False
# df['ALGORITHM'] = True if isinstance(df_merged['LOWER_BOUND'], float) else False
df['N'] = df_merged['N']
df['M'] = df_merged['M']
df['COLUMN_GEN'] = df_merged['LOWER_BOUND'].notna()
df['ALGORITHM'] = df_merged['ALGO_LOWER_BOUND'].notna()
df['CG_LOWER'] = df_merged['LOWER_BOUND']
df['CG_UPPER'] = df_merged['UPPER_BOUND']
df['DIFF_LOWER'] = df_merged['LOWER_BOUND']-df_merged['ALGO_LOWER_BOUND']
df['DIFF_UPPER'] = df_merged['UPPER_BOUND']-df_merged['ALGO_UPPER_BOUND']
df['TRUE_VALUE'] = df_merged['TRUE_VALUE']
df['CG_TIME'] = df_merged['TOTAL_SECONDS_TAKEN']
df['ALGORITHM_TIME'] = df_merged['ALGO_BOUNDS_SECONDS_TAKEN']
df['CG_LOWER_Ite'] = df_merged['LOWER_BOUND_REQUIRED_ITERATIONS']
df['CG_UPPER_Ite'] = df_merged['UPPER_BOUND_REQUIRED_ITERATIONS']
df['CG_BOUNDS_SIZE'] = df_merged['BOUNDS_SIZE']
df.to_csv("refactored_merged_bounds.csv", index=False)

In [20]:
df = pd.read_csv("refactored_merged_bounds.csv")
df

,N,M,COLUMN_GEN,ALGORITHM,CG_LOWER,CG_UPPER,DIFF_LOWER,DIFF_UPPER,TRUE_VALUE,CG_TIME,ALGORITHM_TIME,CG_LOWER_Ite,CG_UPPER_Ite,CG_BOUNDS_SIZE
0,1,1,True,True,0.108661,0.126589,0.000000e+00,0.000000e+00,0.117192,0.749369,0.661149,7,6,0.017929
1,2,1,True,True,0.539263,0.741965,-1.110223e-16,-1.110223e-16,0.543601,0.270833,1.548771,13,14,0.202702
2,4,1,True,True,0.535113,0.765015,1.110223e-16,0.000000e+00,0.537535,15.974915,410.559574,77,107,0.229903
3,3,1,True,True,0.103558,0.123781,0.000000e+00,-9.714451e-17,0.115301,1.814951,106.186425,46,34,0.020223
4,5,1,True,True,0.097862,0.119765,0.000000e+00,-1.110223e-16,0.109848,1047.445045,7173.897312,393,227,0.021903
5,1,2,True,True,0.108871,0.128433,0.000000e+00,0.000000e+00,0.118882,0.215571,4.649352,16,11,0.019562
6,2,2,True,True,0.551997,0.617712,0.000000e+00,-1.110223e-16,0.555954,0.866675,2493.832186,40,36,0.065715
7,3,2,True,False,0.095657,0.117456,NaN,NaN,0.106307,94.491853,NaN,198,165,0.021799
8,4,2,True,False,0.546623,0.621961,NaN,NaN,0.553581,4359.927188,NaN,834,599,0.075338
9,1,3,True,True,0.107029,0.126854,0.000000e+00,-1.110223e-16,0.116733,0.206602,4206.929769,86,55,0.019824
10,2,3,True,False,0.546848,0.615166,NaN,NaN,0.551603,6.642606,NaN,142,119,0.068317
11,3,3,True,False,0.103332,0.123310,NaN,NaN,0.115515,3138.142384,NaN,1651,1591,0.019978